# Generated by Django 3.0.3 on 2020-11-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='detail',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
