# Generated by Django 3.0.3 on 2020-11-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_expense_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='detail',
            field=models.TextField(default=None, max_length=500, null=True),
        ),
    ]
