# Generated by Django 3.0.3 on 2020-11-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201107_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='detail',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
