# Generated by Django 3.0.3 on 2020-11-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='budget',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
